### ISSUE TITLE
`fastify not found, proceeding anyway` if running ES module Node.js program

### ISSUE THREAD

**Issue by coreyfarrell** [fastify/fastify-plugin#101]
## 💥 Regression Report

Loading plugins which use `fastify-plugin` produces a warning message when running a native ES module program.

## Last working version

Worked up to version: 2.0.2

Stopped working in version: 2.0.3

## To Reproduce

Install latest fastify and fastify-static, run the following script.mjs (tested in Node.js 14.8.0):
```js
// script.mjs
import fastifyStatic from 'fastify-static';
```

## Expected behavior

fastify-static should validate the expected version of fastify is installed, nothing should display.  Instead it prints:
```
fastify not found, proceeding anyway
```

Adding a printout of the exception shows `TypeError: Cannot read property 'filename' of undefined`.

## Your Environment

- *node version*: 14.8.0
- *fastify version*: 3.2.1
- *os*: Linux
- Looks to be caused by #94 and #97

**Comment by Eomm** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by fox1t** [comment]
I've just tested this and I am not able to reproduce it. Can you provide a full repro repo?

**Comment by fox1t** [comment]
I had to use this in order to set the root folder for `fastify-static`:
```js
fastify.register(fastifyStatic, {
  root: join(dirname(fileURLToPath(import.meta.url)), "static"),
});
```

**Comment by fox1t** [comment]
Ok I found the line that throws in ESM contexts: https://github.com/fastify/fastify-plugin/blob/master/plugin.js#L89
