### ISSUE TITLE
Make plugin name more accessible

### ISSUE THREAD

**Issue by mnpenner** [fastify/fastify-plugin#155]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

If I create a plugin like...

```ts
// database.ts 
const plugin: FastifyPluginAsync = async (api, options) => {
    api.decorate('db', null)
    // impl details
}

export default fp(plugin, {name:'db'})
```

And then I want to have another plugin that depends on that one but I don't want to hardcode the name, I can do it like this:

```ts
import dbPlugin from './database'

const plugin: FastifyPluginAsync = async (api, options) => {
    api.decorateRequest('user', null)
    // details
}

export default fp(plugin, {name:'user',dependencies:[dbPlugin.default[Symbol.for('fastify.display-name')]]})
```

But `.default[Symbol.for('fastify.display-name')]` is kind of a funky way to extract the plugin name.

Couldn't we add `.pluginName` directly to the the return function from `fp`? Or if you want to keep it a little more hidden, then can Fastify export these Symbols instead of having us reverse-engineer to find out what they are?

### Motivation

Given above. Want easier access to this var. Also, TypeScript is freaking out when I try to access `dbPlugin.default[Symbol.for('fastify.display-name')]]`

### Example

Above.

**Comment by climba03003** [comment]
I think `dbPlugin[Symbol.for('fastify.display-name')]` should works?

**Comment by mnpenner** [comment]
Oh.. I see what I did now. I had `import * as plugin from './myplugin'` instead of just `import plugin from './mypluigin'`. Yes, it works with or without `.default`.

Would be nice to at least get TS to recognize it. 

I tried addinig

```ts
export const fastifyPluginName = Symbol.for('fastify.display-name')
export const fastifyPluginMeta = Symbol.for('plugin-meta')
export const fastifySkipOverride = Symbol.for('skip-override')

declare module 'fastify' {
    interface FastifyPluginAsync<Options> {
        [fastifySkipOverride]: boolean
        [fastifyPluginMeta]: unknown
        [fastifyPluginName]: string
    }
}
```

But it doesn't seem to help.

**Comment by climba03003** [comment]
I am not sure how to improve the type. `symbol` property is a tricky one in TypeScript
