### ISSUE TITLE
missing v4 release?

### ISSUE THREAD

**Issue by Mazuh** [fastify/fastify-plugin#187]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

from the README, it says
> Note: the v4.x series of this module covers Fastify v4

but no v4 of this package is listed here in github.

impact: this is blocking fastify updates on other packages, because of this errors like the above

> (node:87427) UnhandledPromiseRejectionWarning: FastifyError: fastify-plugin: fastify-cors - expected '3.x' fastify version, '4.2.0' is installed

**Comment by mcollina** [comment]
To solve your problem you need to update fastify-cors to `@fastify/cors`. You should be seeing a deprecation message about this.

Shipping a new release for this is not strictly needed, but I'll do do it asap.

**Comment by mcollina** [comment]
Done

**Comment by joelmukuthu** [comment]
Hi @mcollina, do I understand correctly that there are no breaking changes in fastify-plugin v4?

**Comment by mcollina** [comment]
We dropped support for older node.js versions.
