### ISSUE TITLE
Introduce an option to encapsulate the plugin

### ISSUE THREAD

**Issue by dwickern** [fastify/fastify-plugin#197]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Introduce an option `encapsulate?: boolean`. Defaults to `false`. When set to `true`, keep the plugin encapsulated.

### Motivation

`fastify-plugin` currently makes all plugins accessible by setting `skip-override`. It would be nice to have an option to keep it encapsulated, so you can set a plugin's name, metadata, etc without affecting the plugin's scope. 

Would you consider a PR for this?

### Example

```js
module.exports = fp(plugin, {
  fastify: '4.x',
  decorators: {
    fastify: ['plugin1', 'plugin2'],
    reply: ['compress']
  },
  dependencies: ['plugin1-name', 'plugin2-name'],
  encapsulate: true,
})
```

**Comment by Eomm** [comment]
I think it is a good suggestion, but I suspect that something will not work (such as the `name` option) - so we will need a good test suite to cover the use cases

**Comment by climba03003** [comment]
> I suspect that something will not work

I do not get what's you mean by `name` option would not works?
The `name` doesn't matter if it is `encapsulated` or not. It will be pushed to the `registered list` in [any case](https://github.com/fastify/fastify/blob/6dcb5bdce44b3cebcd1e0171a0c59be88caa334d/lib/pluginUtils.js#L132).
