### ISSUE TITLE
Needs a release.

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-plugin#22]
There should be a new release issued so that plugins can be made compatible with Fastify `rc` releases.

**Comment by mcollina** [comment]
already done: https://www.npmjs.com/package/fastify-plugin

**Comment by jsumners** [comment]
I was going on https://github.com/fastify/fastify-plugin/releases which shows 0.2.1 from back in December.

**Comment by mcollina** [comment]
I think we just miss a tag, would you do the honors?

**Comment by jsumners** [comment]
I do not have permission.

**Comment by mcollina** [comment]
Done.
