### ISSUE TITLE
broken with fasitify 1.0.0-rc.2

### ISSUE THREAD

**Issue by balzaczyy** [fastify/fastify-plugin#24]
Error: fastify-plugin - expected '>=0.31.0' fastify version, '1.0.0-rc.2' is installed

**Comment by mcollina** [comment]
which plugin are you using?

**Comment by balzaczyy** [comment]
Oops. I meant to create the issue report in the fastify-response-time repo.
https://github.com/lolo32/fastify-response-time/issues/3

I have no clue and suspect it could be related to semver.
