### ISSUE TITLE
Document plugin name

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify-plugin#28]
In [fastify](https://github.com/fastify/fastify/blob/master/lib/pluginUtils.js#L57) we reference hard to `meta.name` to validate the dependency graph. We should document it and explain the relation.

**Comment by delvedor** [comment]
Pr? :)

**Comment by StarpTech** [comment]
Yes, of course.

**Comment by SerayaEryn** [comment]
I am closing this because the plugin name was documented by #47.
