### ISSUE TITLE
Propagating the Plugin type

### ISSUE THREAD

**Issue by yuriy-yarosh** [fastify/fastify-plugin#36]
So, I'm impl some basic TS typings for `fastify-static` in here [#66](https://github.com/fastify/fastify-static/issues/66). I've made a PR but @mcollina asked me explicitly to make `fastify` a development dependency.

I need a propagated `fastify.Plugin` type for that, and some generic type parameters like `HttpServer / HttpRequest / HttpResponse`. I've created the respective issue in `fastify` too [#970](https://github.com/fastify/fastify/issues/970).

Plugin type has too many type parameters, so I need to know if it's fine to drop the excessive ones first, before making any PR's.

**Comment by jannikkeye** [comment]
@yuriy-yarosh Typings for fustily-static already exist on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/fastify-static/index.d.ts). Those work and do not need fastify-plugin, maybe you can align your typings with the ones on definitelytyped which have been created in accordance with the fastify docs on typings.

**Comment by mcollina** [comment]
I think this could be closed, as some conclusion has been found in https://github.com/fastify/fastify/issues/970.
