### ISSUE TITLE
Add support for "default" export behavior in ECMAScript Modules

### ISSUE THREAD

**Issue by nurdism** [fastify/fastify-plugin#60]
Using babble to write my plugins, running into an issue with `export default foo`. Simple fix/solution would be to add :
```js
  if (typeof fn.default !== "undefined" ) {
    fn = fn.default
  }
``` 
before https://github.com/fastify/fastify-plugin/blob/master/index.js#L8

**Comment by mcollina** [comment]
Would you like to send a PR to add this? 
Would this just support transpiled modules, or actual node syntax with `.mjs`?

**Comment by nurdism** [comment]
this is just for transpiled modules from babel, and yeah I can make a quick PR for it
