### ISSUE TITLE
Fix unorganized test structure

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify-plugin#62]
I was reviewing this repo recently and noticed the unit-tests are unorganized. There is a root level `types.test.ts` file and then within the `tests/` directory there are normal `.js` and `.ts` files. I'm going to take a stab at cleaning this up and additionally expose any missing typings or what not.

**Comment by fox1t** [comment]
This issue was resolved by [63](https://github.com/fastify/fastify-plugin/pull/63) and others.
