### ISSUE TITLE
Fastify 2.0 support

### ISSUE THREAD

**Issue by karlos1337** [fastify/fastify-plugin#66]
Can't build my app since Fastify 2 upgrade, fastify-plugin breaks with:

`Error: fastify-plugin - expected '^1.0.0' fastify version, '2.0.0' is installed`

On removing that check from fastify-plugin source (~ line 65) all works fine again, not a suggestion, for sure will exists a better fix than that :sweat_smile: , but seems that this check is the only problem.

**Comment by mcollina** [comment]
One of the plugins you are using requires fastify v1. If you look at the stacktrace you'll see which one.

**Comment by karlos1337** [comment]
You're right, related with https://github.com/fastify/fastify-cors/issues/17 , sorry
