### ISSUE TITLE
Prefix support in the options

### ISSUE THREAD

**Issue by mhtsharma948** [fastify/fastify-plugin#78]
I was trying to add the prefix for the routes as documented [here](https://www.fastify.io/docs/latest/Routes/#route-prefixing), but there I found that we cannot use the `prefix` option with fastify-plugin.

>  Be aware that if you use fastify-plugin this option won't work. ( see in the route-prefixing docs).

How can we add a prefix with the fastify-plugin package?

**Comment by RafaelGSS** [comment]
can provide a code example that you tried?

**Comment by mhtsharma948** [comment]
Here is my code

**server.ts**
```
        fastify.register(FastifyBlipp);
        fastify.register(require("./modules/user/route/user.route"), {prefix: '/v1'});
```
**user.route.ts**
```
import * as fastifyPlugin from "fastify-plugin";

export default fastifyPlugin(async (server, opts, next) => {
  server.route({
    url: "/user",
    logLevel: "warn",
    method: ["GET", "HEAD"],
    handler: async (request, reply) => {
      return reply.send({ date: new Date(), works: true });
    }
  });
})
```

**Expected result:**
The route should be `/v1/user`

**Result observed**
The available route is `/user`

**Observation**
Prefix option is not working with fastify-plugin.

**Comment by mcollina** [comment]
As per our docs, prefix is not enacted when using fastify-plugin.

Why are you doing it? 

Check out https://github.com/mcollina/fastify-gql/blob/master/index.js to see how to combine them.

**Comment by mhtsharma948** [comment]
I wanna have different versions of APIs. so it would be like `/v1/user` for old version and `v2/user` for the new version.
If we can't use prefix option, how to achieve that, do I have to add `/v2` in all my new APIs?

**Comment by mcollina** [comment]
Just do not use fastify-plugin for wrapping your routes.

**Comment by jsumners** [comment]
@mhtsharma948 @mcollina is specifically talking about Fastify's default scope handling.

See https://www.fastify.io/docs/latest/Plugins/ and https://jrfom.com/posts/2018/03/07/fastify-story/

**Comment by Devendra0110** [comment]
Will there be support for that in the future?

**Comment by mcollina** [comment]
There is no need for it.

```js
module.exports = fp(async function (app, opts) [
  const { prefix } = opts

  app.decorate('something', ...)

  app.register(async function (app) {
     // place your routes here
  }, { prefix } )
}, {
  name: 'myplugin'
})
```

This technique is used in https://github.com/mcollina/fastify-gql.

**Comment by Cheprer** [comment]
Hi I want to re-open this thread since I'm having issue with technique above as also described in docs. I'm using latest at the moment `fastify`: `4.5.3` and `fastify-plugin`: `4.2.1.`

## Structure:

app/v1/system/routes.ts
app/v1/system/plugin.ts
app/index.ts

## Not catching prefix code:
```
// in app/v1/system/routes.ts

import { FastifyInstance, FastifyPluginOptions, FastifyRequest } from 'fastify'
import fp from 'fastify-plugin'

export default fp(
  async (fastify: FastifyInstance, opts: FastifyPluginOptions): Promise<void> => {
    fastify.route({
      handler: function (request: FastifyRequest) {
        console.log(request.body)

        return { hello: 'ok' }
      },
      method: 'POST',
      schema: {
        body: { $ref: 'generated#/definitions/Setup' },
      },
      url: '/setup',
    })
  },
)

// in app/v1/system/plugin.ts

import { FastifyInstance, FastifyPluginOptions } from 'fastify'
import fp from 'fastify-plugin'

import routes from './routes'

export default fp(
  async (fastify: FastifyInstance, options: FastifyPluginOptions): Promise<void> => {
    fastify.register(routes, { prefix: '/v1/system' })
  },
  { name: 'api-v1-system' },
)

// in app/index.ts

  const api = fastify({
    logger: {
      level: logLevel,
      messageKey: 'message',
    },
  })

  await api.register(fastifyOverview)

  api.addSchema({
    $id: 'generated',
    ...generatedSchema,
  })

  // register routes
  await api.register(apiV1System)
```

## Result 
Route is available on `/setup` path. Checking with curl or `fastify-overview`

```
  "routes": [
    {
      "method": "POST",
      "url": "/setup",
      "prefix": "",
      "hooks": {
        "onRequest": [],
        "preParsing": [],
        "preValidation": [],
        "preHandler": [],
        "preSerialization": [],
        "onError": [],
        "onSend": [],
        "onResponse": [],
        "onTimeout": []
      }
    },
```

**Comment by Eomm** [comment]
By using the `fastify-plugin` in `in app/v1/system/routes.ts` the context is not being created, so the prefix is `ignored`

**Comment by Cheprer** [comment]
Ok, ideas how to transform it and also keep the advantage of for example checking dependencies (other plugins) like it can be done in `fastify-plugin`?

**Comment by Cheprer** [comment]
Perfect thank you, played around with it. I wanted to keep ability to check the dependencies in future using `fastify-plugin`. Removed the wrapper on routes and make it as a function accepting fastify instance made it work.
