### ISSUE TITLE
Add node version check for plugins

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify-plugin#79]
##  🚀 Feature Proposal

Hi everyone.

I believe that the minimum node version of plugins maintained by Fastify is the same as Fastify. But, maybe adding a checker for `fastify-plugin` like:
```js
module.exports fp(myPlugin, {
  fastify: '>=1.0.0',
  node: '>=8',
  name: 'my-plugin'
})
```
can be great for plugins that have written with another version of node and for some reason don't send polyfill for it.

If anyone agrees with it, I can send a PR.

**Comment by jsumners** [comment]
I believe this is implied by the Fastify version. One should expect a plugin to run on whatever version of Node the designated Fastify requirement supports.
