### ISSUE TITLE
Better error output

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify-plugin#83]
## 🚀 Feature Proposal

Add the plugin name to the output of the errors

## Motivation

Right now if a module need a fastify version the error is this one:

> Error: fastify-plugin - expected '<2.12.0' fastify version, '2.12.0' is installed

But I don't know which plugin is throwing the error

## Example

> Error: fastify-module-name - expected '<2.12.0' fastify version, '2.12.0' is installed

**Comment by jsumners** [comment]
+1 from me

**Comment by mcollina** [comment]
+1, would you like to send a PR?
