### ISSUE TITLE
`semver.coerce`?

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-plugin#87]
Should `semver.coerce` be used here so that pre-releases of Fastify can be used without requiring an update to this module?

https://github.com/fastify/fastify-plugin/blob/35f3ab7c7d499a4fc7a1c1fc1f7e24d45dcafe2a/plugin.js#L66

**Comment by mcollina** [comment]
I think the top-latest release already allows it. It's implemented via a an old-school regexp. Using `.coerce` would be fantastic.

**Comment by joobisb** [comment]
@mcollina i've raised a PR for this. please have a look
https://github.com/fastify/fastify-plugin/pull/88
