### ISSUE TITLE
Error creating a new TypeScript plugin using `fastify-plugin`

### ISSUE THREAD

**Issue by vinicius0026** [fastify/fastify-plugin#91]
#### You have already researched for similiar issues?
Yes, didn't find anything.

#### What are you trying to achieve or the steps to reproduce?

I'm writing a plugin using `fastify-plugin` in TypeScript. I'm having issues with the types for `fastify-plugin`. I want to declare the types for my plugin and also pass plugin options (with plugin name and dependencies) to the plugin, but these two seem to be coupled in the `fastify-plugin/plugin.d.ts`  type definitions.

This is my plugin code:

```typescript
import fp from "fastify-plugin";

interface Options {
  someOpt: string
}

export default fp(async (server, options: Options) => {
  // do something
}, {
  fastify: "3.x",
  name: "plugin-name",
  dependencies: ["some-deps"],
});
```

#### What was the result you received?

This is the TypeScript error I'm getting:

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ fastify: string; name: string; dependencies: string[]; }' is not assignable to parameter of type 'string'.ts(2769)
```

#### What did you expect?

I expect to be able to declare plugin-specific options types that are decoupled from plugin metadata interface.

The issue seems to come from this type definition:

```typescript
export default function fp<Options>(
  fn: FastifyPluginAsync<Options>,
  options?: Options & PluginOptions,
): FastifyPluginAsync<Options>;
```

where the `Options` type param is combined (using the intersection type operator) with the `PluginOptions` interface. It seems to me that these should not be coupled like that. Maybe something like this would work?

```typescript
export default function fp<Options>(
  fn: FastifyPluginAsync<Options>,
  options?: PluginOptions,
): FastifyPluginAsync<Options>;
```

or, if we need a type param for the plugin metadata interface, maybe something like this:

```typescript
export default function fp<Options, PluginOptions>(
  fn: FastifyPluginAsync<Options>,
  options?: PluginOptions,
): FastifyPluginAsync<Options>;
```

I can move this issue to the `fastify-plugin` repo as a bug if that's appropriate. Thank you!

#### Context

* *node version*:  12
* *typescript version*: 3.9.6
* *fastify-plugin version*: 2.0.1
* *os*: Mac

**Comment by mcollina** [comment]
> @mcollina please correct me if I'm wrong, based on my understanding of the fastify-plugin source code, the fastify-plugin second argument is never passed to the first argument (the actual function). Thus, they should not be joined with the fastify-plugin specific options (i.e. the metadata).

Correct.
